"""Add blogs tables

Revision ID: 5eb1a27ef25b
Revises: 6e01bcd9b230
Create Date: 2025-11-24 21:27:54.572625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5eb1a27ef25b'
down_revision: Union[str, None] = '6e01bcd9b230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.add_column('blogs', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('blogs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('blogs', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_blogs_created_at'), 'blogs', ['created_at'], unique=False)
    op.create_index(op.f('ix_blogs_id'), 'blogs', ['id'], unique=False)
    op.create_index(op.f('ix_blogs_is_deleted'), 'blogs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_blogs_updated_at'), 'blogs', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blogs_updated_at'), table_name='blogs')
    op.drop_index(op.f('ix_blogs_is_deleted'), table_name='blogs')
    op.drop_index(op.f('ix_blogs_id'), table_name='blogs')
    op.drop_index(op.f('ix_blogs_created_at'), table_name='blogs')
    op.drop_column('blogs', 'is_deleted')
    op.drop_column('blogs', 'updated_at')
    op.drop_column('blogs', 'created_at')
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_pkey'))
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    # ### end Alembic commands ###
